version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: TzBVz678Zs3Usc
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: TzBVz678Zs3Usc
      DB_HOST: db
      DB_PORT: 5432
